from enum import Enum

# KEEP ALIVE
HEALTHCHECK_TIMEOUT = 0.5
TIME_BETWEEN_HEALTHCHECKS = 1.0
N_RETRIES_CONTACT_LEADER = 2

# SELF PROCLAIMER
SELF_PROCLAIMER_TIMEOUT = 1.0


# MIDDLEWARE
IP_ADDR_START = "172.25.125."
IP_ADDR_END_BASE = 4
CONNECTION_PORT = 6767

NO_LEADER = None

class Message(Enum):
    ELECTION = b'E'
    COORDINATOR = b'C'
    ELECTION_ACK = b'A'
    LEADER_ALIVE = b'L'
    LEADER_ALIVE_REPLY = b'R'
