from enum import Enum

# KEEP ALIVE
HEALTHCHECK_TIMEOUT = 4.0
MINIMUM_TIME_SLEEP = 1.0
N_RETRIES_CONTACT_LEADER = 2

# SELF PROCLAIMER
SELF_PROCLAIMER_TIMEOUT = 1.0

NO_LEADER = None


class Message(Enum):
    ELECTION = b'E'
    COORDINATOR = b'C'
    ELECTION_ACK = b'A'
    LEADER_ALIVE = b'L'
    LEADER_ALIVE_REPLY = b'R'
